CREATE DATABASE db_titanium

GO

USE db_titanium

CREATE TABLE tb_usuario(
IdUsuario		UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Nome	        NVARCHAR(255)						NOT NULL,
Email	        NVARCHAR(255)		UNIQUE			NOT NULL,
Senha			NVARCHAR (50)		UNIQUE			NOT NULL,
);

CREATE TABLE tb_pedido(
Id				UNIQUEIDENTIFIER PRIMARY KEY DEFAULT ((NEWID())),
Equipamento		NVARCHAR(255),
Localização		NVARCHAR(255) NOT NULL,
Descrição		NVARCHAR(300) NOT NULL,
FotoDoProblema	VARCHAR(2048),
DataDoProblema	DATETIME2,
IdUsuario		UNIQUEIDENTIFIER FOREIGN KEY REFERENCES tb_usuario(IdUsuario)
)